### ISSUE TITLE
Does not add tag for matching `base` branch.

### ISSUE THREAD

**Issue by SpacyRicochet** [ffittschen/pr-branch-labeler#34]
I'm trying to make have a `release` label for any PRs that are to be merged in a release branch (e.g. `release/1.0.1`). However, this doesn't appear to be working, as the `release` label is never added. Other labels are added however, such as the `chore` label, which is done because the `head` is names `chore/some-branch-name`.

This is the configuration;

HEAD: `chore/pr-labeler`
BASE: `release/3.15`

Configuration file (`.github/pr-branch-labeler.yml`);
```
# Apply label "release" is base matches "release/*"
release:
  base: ["release/**"]

# Apply label "feature" if head matches "feature/*"
feature:
  head: ["feature/*"]

# Apply label "bugfix" if head matches one of "bugfix/*" or "hotfix/*"
bugfix:
  head: ["bugfix/*", "hotfix/*"]

# Apply label "chore" if head matches one of "chore/*" or "maintenance/*"
chore:
  head: ["chore/*", "maintenance/*"]
```

Workflow action;
```
name: PR Preflight

on:
  pull_request:

jobs:
  label_prs:
    runs-on: macOS-11
    steps:
    - name: Label PRs
      uses: ffittschen/pr-branch-labeler@v1
      with:
        repo-token: ${{ github.token }}
```
