### ISSUE TITLE
Cannot get it to add any labels

### ISSUE THREAD

**Issue by AndrewLeedham** [ffittschen/pr-branch-labeler#4]
I don't seem to be able to get this action to add any labels.
Using the following workflow:
```yaml
on:
  pull_request:
    types: [opened]
name: Add base branch label
jobs:
  base-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Add base branch label
        uses: ffittschen/pr-branch-labeler@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```
and the following `pr-branch-labeler.yml`
```yaml
development:
  base: 'development'

stage:
  base: 'stage'

master:
  base: 'master'
```
The workflow is running, but there is no output (tested with both draft and normal PR) base branch was "development".

Unfortunately I am trying this in a private repo, otherwise I would share a link, but here are some screenshots:
![image](https://user-images.githubusercontent.com/5557458/82075512-44386080-96d4-11ea-8c3f-f951ca1e5be4.png)

![image](https://user-images.githubusercontent.com/5557458/82075538-4bf80500-96d4-11ea-8556-993c2c1fdbf0.png)

![image](https://user-images.githubusercontent.com/5557458/82075622-6cc05a80-96d4-11ea-922a-74dda8846b41.png)
