### ISSUE TITLE
Error: Bad credentials

### ISSUE THREAD

**Issue by chaturvedisumit** [ffittschen/pr-branch-labeler#42]
I am running the labeler WF on an enterprise repo and it gives me the bad credentials error.

While running the same on a personal repo, it works smoothly. Not able to debug the issue.

**Workflow :**

```
name: PR Branch Labeler

on: pull_request

jobs:
  label_prs:
    runs-on: [<runner labels>]
    steps:
    - name: Label PRs
      if: github.event.action == 'opened' # Only run the action when the PR was first opened
      uses: ffittschen/pr-branch-labeler@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
```

**Config :**

```
# Apply label "feature" if head matches "feature/*"
major:
  head: feature/*

# Apply label "bugfix" if head matches "bugfix/*"
minor:
  head: "bugfix/*"

patch:
  head: "hotfix/*"
```
